-- MySQL Script generated by MySQL Workbench
-- Seg 12 Jun 2017 16:44:05 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ru
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ru
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ru` DEFAULT CHARACTER SET utf8 ;
USE `ru` ;

-- -----------------------------------------------------
-- Table `ru`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ru`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `ru`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nivel` INT NOT NULL,
  `registro_academico` INT NULL,
  `registro_universitario` INT NULL,
  `criado_em` DATETIME NULL,
  `atualizado_em` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ru`.`transacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ru`.`transacoes` ;

CREATE TABLE IF NOT EXISTS `ru`.`transacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(8,2) NOT NULL,
  `criado_em` DATETIME NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transacoes_usuarios_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_transacoes_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ru`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
